name: mast
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  analyzer: ^5.2.0
  animated_bottom_navigation_bar: ^1.1.0+1
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.0.2
  bloc: ^8.0.3
  upgrader: ^4.6.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.2.1
  circle_nav_bar: ^2.0.1+1
  circular_bottom_navigation: ^2.3.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^4.0.6
  equatable: ^2.0.3
  file_picker: ^5.0.1
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2
  flash: ^2.0.3+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^12.0.4
  flutter_localizations:
    sdk: flutter
  flutter_native_image: ^0.0.6+1
  flutter_native_splash: ^2.2.4
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.0
  freezed: ^2.0.3+1
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_fonts: ^4.0.1
  google_maps_flutter: ^2.2.1
  image_card: ^0.0.4
  image_picker: ^0.8.5+3
  infinite_scroll_pagination: ^3.2.0
  injectable: ^2.0.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  json_annotation: ^4.5.0
  json_serializable: ^6.1.4
  lottie: ^2.0.0
  material_dialogs: ^1.1.4
  motion_toast: ^2.1.9
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  persistent_bottom_nav_bar: ^5.0.2
  pinput: ^2.2.12
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  stacked_card_carousel: ^0.0.4
  url_launcher: ^6.1.5
  url_launcher_android: ^6.0.23
  url_launcher_ios: ^6.0.18

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.0.1
  retrofit_generator: ^4.0.1

# flutter packages pub run build_runner watch --delete-conflicting-outputs
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/json/
  fonts:
    - family: bank
      fonts:
        - asset: assets/fonts/ar/bank_Bold.ttf
          weight: 700
        - asset: assets/fonts/ar/bank_Regular.ttf
          weight: 400

flutter_native_splash:

  color: "#FFFFFF"
  # background_image: "assets/splash.png"
  image: assets/splash.png

  android: true
  ios: true
  #web: false
